# Generated by Django 4.0.2 on 2022-02-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not available'), ('o', 'On loan'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
